### ISSUE TITLE
Norton Security problems with "find-multi.exe"

### ISSUE THREAD

**Issue by MRC3742** [benlye/MultiBootReloader#1]
I know you're still working on this but I just downloaded it to give it a try.
I downloaded/opened the MULTI-BootReloader-0.1.0.zip file using 7-Zip and extracted it to my C:\temp folder. Norton Security immediately removed "find-multi.exe" to quarantine. I then had to restore it and exclude it from future scans.

I was then able to run Upgrade-Multi-Bootloader.bat and all appears to have updated successfully!
Not sure you can do anything about it but just some feedback.
OS: Windows 7 (32bit)
MPM: External IRX4+

Thanks for all your work and time on the Multi project - Rich

![Norton1](https://user-images.githubusercontent.com/26642502/83339968-0d9c4180-a2a1-11ea-9043-e4163279ef83.png)

**Comment by benlye** [comment]
Hopefully after a few more downloads that will go away - it seems to be purely reputation based.  If you can submit a false-positive report to Norton it may help.

**Comment by benlye** [comment]
I've just published the source of find-multi.exe on Github.  If you have a minute, can you download the release zip file from there as well?  It might help improve the Norton reputation score.

https://github.com/benlye/find-multi

Thanks!

**Comment by MRC3742** [comment]
I've now submitted a false positive report to Norton.
And also downloaded it from the find-multi github site.

Thanks - Rich
